services:

  backend:
    build: ./backend
    container_name: chatbot-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: chatbot-frontend
    ports:
      - "80:80"
    depends_on:
      - backend